name = "fi-video-serve"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "FI_FILMS"
bucket_name = "fi-films"

[[kv_namespaces]]
binding = "PASSWORDS"
id = "fa7b776cda67483596f902714d749d3c"
