#!/usr/bin/env node
/**
 * Batch Delivery Shell Generator
 *
 * Pre-generates video-empty delivery page shells for many couples at once.
 * Shells are valid, on-brand pages that render a "Your films are on the way."
 * message until a video source is attached. On delivery day Studio writes the
 * couple's video source to the delivery config API and the already-deployed
 * page picks it up at LOAD TIME, with no regeneration needed.
 *
 * Each couple is generated by shelling out to generate-film-page.js with a
 * temp config of { slug, coupleNames, weddingDate, videos: [] }, so all the
 * canonical validation, normalization, and token replacement live in exactly
 * one place (no duplicated generator logic here).
 *
 * Usage:
 *   node delivery/generate-batch.js <couples.json>
 *   node delivery/generate-batch.js <couples.json> --output-root ../films
 *   node delivery/generate-batch.js <couples.json> --config-api-base https://prep.flyiniris.com
 *   node delivery/generate-batch.js <couples.json> --worker-base https://video.flyiniris.com
 *
 * couples.json schema: an array of
 *   { "slug": "amanda-boris", "coupleNames": "Amanda & Boris", "weddingDate": "August 31, 2025" }
 */

const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');

const GENERATOR = path.join(__dirname, 'generate-film-page.js');

function parseArgs(argv) {
  const args = argv.slice(2);
  const out = { couplesPath: null, passthrough: [] };
  for (let i = 0; i < args.length; i++) {
    if ((args[i] === '--output-root' || args[i] === '--config-api-base' || args[i] === '--worker-base') && args[i + 1]) {
      out.passthrough.push(args[i], args[i + 1]);
      i++;
    } else if (!out.couplesPath) {
      out.couplesPath = args[i];
    }
  }
  return out;
}

function printUsageAndExit() {
  console.error('Usage: node generate-batch.js <couples.json> [--output-root <dir>] [--config-api-base <url>] [--worker-base <url>]');
  console.error('');
  console.error('couples.json: an array of { slug, coupleNames, weddingDate }');
  console.error(JSON.stringify([
    { slug: 'amanda-boris', coupleNames: 'Amanda & Boris', weddingDate: 'August 31, 2025' },
    { slug: 'jessica-tyler', coupleNames: 'Jessica & Tyler', weddingDate: 'September 25, 2026' },
  ], null, 2));
  process.exit(1);
}

function main() {
  const { couplesPath, passthrough } = parseArgs(process.argv);
  if (!couplesPath) printUsageAndExit();

  const absPath = path.resolve(couplesPath);
  let couples;
  try {
    couples = JSON.parse(fs.readFileSync(absPath, 'utf-8'));
  } catch (e) {
    console.error(`Failed to read or parse couples file at ${absPath}: ${e.message}`);
    process.exit(1);
  }

  if (!Array.isArray(couples) || couples.length === 0) {
    console.error('couples.json must be a non-empty array of { slug, coupleNames, weddingDate }.');
    process.exit(1);
  }

  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'fi-batch-'));
  const results = { ok: [], failed: [] };

  for (let i = 0; i < couples.length; i++) {
    const c = couples[i] || {};
    const label = c.slug || `index ${i}`;

    // Build a video-empty shell config. The generator validates slug,
    // coupleNames, and weddingDate; let it own those error messages.
    const shellConfig = {
      slug: c.slug,
      coupleNames: c.coupleNames,
      weddingDate: c.weddingDate,
      videos: [],
    };

    const tmpConfig = path.join(tmpDir, `${(c.slug || 'couple-' + i)}.json`);
    try {
      fs.writeFileSync(tmpConfig, JSON.stringify(shellConfig), 'utf-8');
      execFileSync('node', [GENERATOR, tmpConfig, ...passthrough], { stdio: 'inherit' });
      results.ok.push(label);
    } catch (e) {
      results.failed.push(label);
      console.error(`  FAILED: ${label} (${e.message})`);
    }
  }

  try { fs.rmSync(tmpDir, { recursive: true, force: true }); } catch (e) { /* best effort cleanup */ }

  console.log('');
  console.log('===== Batch summary =====');
  console.log(`  Total:     ${couples.length}`);
  console.log(`  Generated: ${results.ok.length}`);
  console.log(`  Failed:    ${results.failed.length}`);
  if (results.failed.length > 0) {
    console.log(`  Failed slugs: ${results.failed.join(', ')}`);
    process.exit(1);
  }
}

main();
