#!/usr/bin/env node
/**
 * Batch Delivery Shell Generator
 *
 * Pre-generates video-empty delivery page shells for many couples at once.
 * Shells are valid, on-brand pages that render a "Your films are on the way."
 * message until a video source is attached. On delivery day Studio writes the
 * couple's video source to the delivery config API and the already-deployed
 * page picks it up at LOAD TIME, with no regeneration needed.
 *
 * Each couple is generated by shelling out to generate-film-page.js with a
 * temp config of { slug, coupleNames, weddingDate, videos: [] }, so all the
 * canonical validation, normalization, and token replacement live in exactly
 * one place (no duplicated generator logic here).
 *
 * Usage:
 *   node delivery/generate-batch.js <couples.json>
 *   node delivery/generate-batch.js <couples.json> --output-root ../films
 *   node delivery/generate-batch.js <couples.json> --config-api-base https://prep.flyiniris.com
 *   node delivery/generate-batch.js <couples.json> --worker-base https://video.flyiniris.com
 *
 *
 * One couple, no file (the one-command shell for a new slug):
 *   node delivery/generate-batch.js --slug jessica-tyler --names "Jessica & Tyler" --date "September 25, 2026"
 *
 * One business (client) page: --client switches to kind business; --subtitle
 * and --date are optional (subtitle defaults to "Films by Flyin' Iris"):
 *   node delivery/generate-batch.js --slug window-world --client "Window World" --subtitle "Films by Flyin' Iris"
 *
 * couples.json schema: an array of
 *   { "slug": "amanda-boris", "coupleNames": "Amanda & Boris", "weddingDate": "August 31, 2025" }
 * or for a client: { "kind": "business", "slug": "window-world", "clientName": "Window World", "subtitle": "...", "eventDate": "..." }
 */

const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');

const GENERATOR = path.join(__dirname, 'generate-film-page.js');

function parseArgs(argv) {
  const args = argv.slice(2);
  const out = { couplesPath: null, passthrough: [], single: {}, force: false };
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--force') {
      out.force = true;
    } else if ((args[i] === '--slug' || args[i] === '--names' || args[i] === '--date' || args[i] === '--client' || args[i] === '--subtitle') && args[i + 1] != null) {
      out.single[args[i].slice(2)] = args[i + 1];
      i++;
    } else if ((args[i] === '--output-root' || args[i] === '--config-api-base' || args[i] === '--worker-base') && args[i + 1]) {
      out.passthrough.push(args[i], args[i + 1]);
      i++;
    } else if (!out.couplesPath) {
      out.couplesPath = args[i];
    }
  }
  return out;
}

function printUsageAndExit() {
  console.error('Usage: node generate-batch.js <couples.json> [--output-root <dir>] [--config-api-base <url>] [--worker-base <url>]');
  console.error('Add --force to replace an existing page that still has baked videos.');
  console.error('   or: node generate-batch.js --slug <slug> --names "Name1 & Name2" --date "Month D, YYYY" [same flags]');
  console.error('   or: node generate-batch.js --slug <slug> --client "Client Name" [--subtitle "..."] [--date "Month D, YYYY"] [same flags]');
  console.error('');
  console.error('couples.json: an array of { slug, coupleNames, weddingDate }');
  console.error(JSON.stringify([
    { slug: 'amanda-boris', coupleNames: 'Amanda & Boris', weddingDate: 'August 31, 2025' },
    { slug: 'jessica-tyler', coupleNames: 'Jessica & Tyler', weddingDate: 'September 25, 2026' },
  ], null, 2));
  process.exit(1);
}

function bakedVideoCount(indexPath) {
  let html;
  try { html = fs.readFileSync(indexPath, 'utf-8'); } catch (e) { return 0; }
  const m = html.match(/(?:var|const) VIDEOS = (\[.*?\]);/);
  if (!m) return 0;
  try { return JSON.parse(m[1]).length; } catch (e) { return 1; }
}

function main() {
  const { couplesPath, passthrough, single, force } = parseArgs(process.argv);
  const outIdx = passthrough.indexOf('--output-root');
  const outputBase = outIdx >= 0
    ? path.resolve(passthrough[outIdx + 1])
    : path.resolve(__dirname, '..', 'films');
  const singleMode = Object.keys(single).length > 0;
  if (!couplesPath && !singleMode) printUsageAndExit();
  if (couplesPath && singleMode) {
    console.error('Pass either a couples.json file or --slug/--names/--date, not both.');
    process.exit(1);
  }

  let couples;
  if (singleMode) {
    couples = single.client !== undefined
      ? [{ kind: 'business', slug: single.slug, clientName: single.client,
           ...(single.subtitle ? { subtitle: single.subtitle } : {}),
           ...(single.date ? { eventDate: single.date } : {}) }]
      : [{ slug: single.slug, coupleNames: single.names, weddingDate: single.date }];
  } else {
    const absPath = path.resolve(couplesPath);
    try {
      couples = JSON.parse(fs.readFileSync(absPath, 'utf-8'));
    } catch (e) {
      console.error(`Failed to read or parse couples file at ${absPath}: ${e.message}`);
      process.exit(1);
    }
  }

  if (!Array.isArray(couples) || couples.length === 0) {
    console.error('couples.json must be a non-empty array of { slug, coupleNames, weddingDate }.');
    process.exit(1);
  }

  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'fi-batch-'));
  const results = { ok: [], failed: [] };

  for (let i = 0; i < couples.length; i++) {
    const c = couples[i] || {};
    const label = c.slug || `index ${i}`;

    // Build a video-empty shell config. The generator validates slug,
    // coupleNames, and weddingDate; let it own those error messages.
    const shellConfig = c.kind === 'business'
      ? {
          kind: 'business',
          slug: c.slug,
          clientName: c.clientName,
          ...(c.subtitle !== undefined ? { subtitle: c.subtitle } : {}),
          ...(c.eventDate !== undefined ? { eventDate: c.eventDate } : {}),
          ...(c.eventLinks !== undefined ? { eventLinks: c.eventLinks } : {}),
          videos: [],
        }
      : {
          ...(c.kind !== undefined ? { kind: c.kind } : {}),
          slug: c.slug,
          coupleNames: c.coupleNames,
          weddingDate: c.weddingDate,
          videos: [],
        };

    // Never overwrite a live page that has baked videos with an empty shell:
    // that would blank the page for any couple whose videos are not yet in
    // delivery_video_config. --force overrides once the API row is seeded.
    if (!force && c.slug && bakedVideoCount(path.join(outputBase, c.slug, 'index.html')) > 0) {
      results.failed.push(label);
      console.error(`  SKIPPED: ${label} already has a page with baked videos. Seed its delivery_video_config row first, then rerun with --force.`);
      continue;
    }

    const tmpConfig = path.join(tmpDir, `${(c.slug || 'couple-' + i)}.json`);
    try {
      fs.writeFileSync(tmpConfig, JSON.stringify(shellConfig), 'utf-8');
      execFileSync('node', [GENERATOR, tmpConfig, ...passthrough], { stdio: 'inherit' });
      results.ok.push(label);
    } catch (e) {
      results.failed.push(label);
      console.error(`  FAILED: ${label} (${e.message})`);
    }
  }

  try { fs.rmSync(tmpDir, { recursive: true, force: true }); } catch (e) { /* best effort cleanup */ }

  console.log('');
  console.log('===== Batch summary =====');
  console.log(`  Total:     ${couples.length}`);
  console.log(`  Generated: ${results.ok.length}`);
  console.log(`  Failed:    ${results.failed.length}`);
  if (results.failed.length > 0) {
    console.log(`  Failed slugs: ${results.failed.join(', ')}`);
    process.exit(1);
  }
}

main();
